name: mkdocs-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v4

      - name: Git 配置
        run: |
          git config --global user.name "shenweiyan"
          git config --global user.email "weiyanshum@gmail.com"

      - name: Git 拉取
        run: git pull

      - name: 安装 Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
